server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    stream:
      binders:
        binderName:
          type: kafka
      bindings:
        myDemoBroadcast:
          destination: demo